"""Add active column to products

Revision ID: 3098fe114a20
Revises: e73d7fdf089d
Create Date: 2026-05-09 16:27:26.930987

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3098fe114a20"
down_revision = "e73d7fdf089d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
