"""empty message

Revision ID: e3809aa6fb0a
Revises: 2c39e1757e70
Create Date: 2026-05-10 22:52:25.545444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3809aa6fb0a'
down_revision = '2c39e1757e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('posted')
        batch_op.drop_column('category')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
